// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCEa50WQDDnP8HFZUit0U4gA3KwkLZ-I',
    appId: '1:339673988370:web:cece29f1e964c4bc6d07cb',
    messagingSenderId: '339673988370',
    projectId: 'falconest-8d060',
    authDomain: 'falconest-8d060.firebaseapp.com',
    storageBucket: 'falconest-8d060.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlyfJjqX8JfUOsch9VUUFDQd3jJt5lbg',
    appId: '1:339673988370:android:1ce9079727e8b42c6d07cb',
    messagingSenderId: '339673988370',
    projectId: 'falconest-8d060',
    storageBucket: 'falconest-8d060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_k5TPuR7wcKlDM0vq4Kshktn05BhG_k',
    appId: '1:339673988370:ios:b16a51779f5ac4096d07cb',
    messagingSenderId: '339673988370',
    projectId: 'falconest-8d060',
    storageBucket: 'falconest-8d060.firebasestorage.app',
    iosBundleId: 'com.example.falconest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1_k5TPuR7wcKlDM0vq4Kshktn05BhG_k',
    appId: '1:339673988370:ios:b16a51779f5ac4096d07cb',
    messagingSenderId: '339673988370',
    projectId: 'falconest-8d060',
    storageBucket: 'falconest-8d060.firebasestorage.app',
    iosBundleId: 'com.example.falconest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASCEa50WQDDnP8HFZUit0U4gA3KwkLZ-I',
    appId: '1:339673988370:web:b302d9d194e6e9536d07cb',
    messagingSenderId: '339673988370',
    projectId: 'falconest-8d060',
    authDomain: 'falconest-8d060.firebaseapp.com',
    storageBucket: 'falconest-8d060.firebasestorage.app',
  );
}
